### ISSUE TITLE
Чем эти исходники отличаются от типовой выгрузки в 8.3.5 ?

### ISSUE THREAD

**Issue by pumbaEO** [elisy/ssl#2]

**Comment by elisy** [comment]
Исходники отличаются тем, что аккуратно сложены по папкам: вид объекта, название, форма, название формы

**Comment by pumbaEO** [comment]
Как победили ограничение в 260 символов в полном наименовании?

**Comment by elisy** [comment]
Никак не побеждал _(еще не сталкивался с таким ограничением)_
